Tricone/Controllers/ProvinsiController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tricone.Models;

namespace Tricone.Controllers
{
    public class ProvinsiController : Controller
    {
        // GET: Provinsi
        DB_TRICONEEntitie dc = new DB_TRICONEEntitie();

        public ActionResult Index()
        {
            ViewBag.Message = "master";
            return View(dc.MS_PROVINSI.ToList());
        }

        /*public ActionResult Getdata()
        {
            List<MS_PROVINSI> provList = dc.MS_PROVINSI.ToList<MS_PROVINSI>();
            return Json(new { data = provList }, JsonRequestBehavior.AllowGet);
        }*/
        [HttpGet]
        public JsonResult Getdata()
        {
            List<MS_PROVINSI> provList = dc.MS_PROVINSI.ToList<MS_PROVINSI>();
            List<ProvOutput> result = new List<ProvOutput>();
            foreach (var item in provList)
            {
                result.Add(new ProvOutput
                {
                    ID_PROVINSI = item.ID_PROVINSI,
                    NAMA_PROVINSI = item.NAMA_PROVINSI
                });
            }

            //var json = Newtonsoft.Json.JsonConvert.SerializeObject(result);
            return Json(new { data = result.OrderByDescending(e=>e.ID_PROVINSI) }, JsonRequestBehavior.AllowGet);
            
        }

        [HttpGet]
        public ActionResult AddorEdit(int id = 0)
        {
            if (id == 0)
            {
                return View(new MS_PROVINSI());
            }
            else
            {
                return View(dc.MS_PROVINSI.Where(x => x.ID_PROVINSI == id).FirstOrDefault<MS_PROVINSI>());
            }
        }

        [HttpPost]
        public ActionResult AddorEdit(MS_PROVINSI prov)
        {
            using (var transactions= dc.Database.BeginTransaction())
            {
                try
                {
                    prov.MODIFIED_DATE = DateTime.Now;
                    if (prov.ID_PROVINSI == 0)
                    {
                        prov.CREATED_DATE = DateTime.Now;
                        dc.MS_PROVINSI.Add(prov);
                        dc.SaveChanges();

                        //audit trail
                        var provin = dc.MS_PROVINSI.OrderByDescending(e => e.ID_PROVINSI).FirstOrDefault();
                        TBL_AUDIT_TRAIL audit = new TBL_AUDIT_TRAIL();
                        audit.NAMA_TABEL = "MS_PROVINSI";
                        audit.AKSI = "ADD";
                        audit.NAMA_FIELD = "All Field";
                        audit.VALUE_LAMA = "";
                        audit.userid = Session["ID_MEMBER"].ToString();
                        audit.VALUE_BARU = provin.ID_PROVINSI+", "+ prov.NAMA_PROVINSI;
                        audit.CREATED_DATE = DateTime.Now;
                        audit.MODIFIED_DATE = DateTime.Now;
                        dc.TBL_AUDIT_TRAIL.Add(audit);
                        dc.SaveChanges();

                        transactions.Commit();
                        return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                    else
                    {
                        var ads = dc.MS_PROVINSI.AsNoTracking().Where(x => x.ID_PROVINSI == prov.ID_PROVINSI).FirstOrDefault();
                        dc.Entry(prov).State = EntityState.Modified;
                        dc.Entry(prov).Property("CREATED_DATE").IsModified = false;
                        dc.SaveChanges();
                        //audit trail
                        
                        TBL_AUDIT_TRAIL audit = new TBL_AUDIT_TRAIL();
                        audit.NAMA_TABEL = "MS_PROVINSI";
                        audit.AKSI = "EDIT";
                        audit.userid = Session["ID_MEMBER"].ToString();
                        audit.NAMA_FIELD = "NAMA_PROVINSI";
                        audit.VALUE_LAMA = prov.ID_PROVINSI + ", " + ads.NAMA_PROVINSI;
                        audit.VALUE_BARU = prov.ID_PROVINSI + ", " + prov.NAMA_PROVINSI;
                        audit.CREATED_DATE = DateTime.Now;
                        audit.MODIFIED_DATE = DateTime.Now;
                        dc.TBL_AUDIT_TRAIL.Add(audit);
                        dc.SaveChanges();

                        transactions.Commit();
                        return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception msgErr)
                {
                    //error log
                    DB_TRICONEEntitie dc2 = new DB_TRICONEEntitie();
                    TBL_EROR_LOG logerror = new TBL_EROR_LOG();
                    if (Session["ID_MEMBER"].ToString() != null)
                    {
                        logerror.ID_USER = Session["ID_MEMBER"].ToString();
                    }
                    logerror.EROR_TIME = DateTime.Now;
                    logerror.EROR_DESCRIPTION = msgErr.Message;
                    logerror.CREATED_DATE = DateTime.Now;
                    logerror.MODIFIED_DATE = DateTime.Now;
                    logerror.EROR_LINE = Convert.ToString(string.Format("StackTrace: {0}", msgErr.StackTrace));
                    dc2.TBL_EROR_LOG.Add(logerror);
                    dc2.SaveChanges();

                    transactions.Rollback();
                    return Json(new { success = true, message = msgErr.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            MS_PROVINSI prov = dc.MS_PROVINSI.Where(x => x.ID_PROVINSI == id).FirstOrDefault<MS_PROVINSI>();
            dc.MS_PROVINSI.Remove(prov);
            dc.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);
        }
    }

    public class ProvOutput
    {
        public int ID_PROVINSI { get; set; }
        public string NAMA_PROVINSI { get; set; }
    }
}

Tricone/Views/Provinsi/AddorEdit.cshtml
@model Tricone.Models.MS_PROVINSI
@{
    Layout = null;
}


@using (Html.BeginForm("AddorEdit", "Provinsi", FormMethod.Post, new { onsubmit = "return SubmitForm(this)" }))
{
    @Html.HiddenFor(model => model.ID_PROVINSI)
    <div class="form-group">
        <div class="col-md-12">
            <label class="control-label">Nama Provinsi<span style="color:red;"> *</span></label>
            @Html.EditorFor(model => model.NAMA_PROVINSI, new { htmlAttributes = new { @class = "form-control col-md-12", @placeholder = "Nama" } })
            <span style="color:red;">@Html.ValidationMessageFor(model => model.NAMA_PROVINSI)</span>
            @ViewBag.Error
        </div>
    </div>
    <div class="form-label-group">
        <div class="container col-sm-12" style="margin-top:10px;">
            <input type="submit" value="submit" class="btn btn-primary" />
            <input type="reset" value="reset" class="btn btn-warning" />
        </div>
    </div>
}

Tricone/Views/Provinsi/Index.cshtml
@model IEnumerable<Tricone.Models.MS_PROVINSI>

@{
    ViewBag.Title = "Index";
}
@ViewBag.Error
<link rel="stylesheet" href="~/Content/jquery-ui.min.css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Master Data
            <small>Provinsi</small>
        </h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-database"></i> Master Data</a></li>
            <li class="active">Provinsi</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">
        <a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddorEdit","Provinsi")')"><i class="fa fa-plus"></i> Create New</a>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>Nama Provinsi</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->
@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js" crossorigin="anonymous"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    <script type="text/javascript">
        var Popup, dataTable;
        $(document).ready(function () {
            var nmor = 0;
            datatable = $('#example1').DataTable({
                "ajax": {
                    "url": "@Url.Action("Getdata", "Provinsi")",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "NAMA_PROVINSI" },
                    {
                        "data": "ID_PROVINSI", "render": function (data) {
                            return "<div style='text-align:center;'><a class='btn btn-primary btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit","Provinsi")/" + data + "')><i class='fa fa-pencil'></i> Edit</a></div>"
                        },
                        "orderable": false,
                        "width":"150px"
                    }
                ], "order": [],
                "language": {
                    "emptyTable":"No Data Found, Please click on <b>Create New</b> Button"
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
            .done(function (response) {
                formDiv.html(response);
                Popup = formDiv.dialog({
                    autoOpen: true,
                    resizable: false,
                    title: 'Fill Provinsi Details',
                    height: 200,
                    width: 500,
                    close: function () {
                        Popup.dialog('destroy').remove();
                    }
                });
            });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: $(form).serialize(),
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            datatable.ajax.reload(null, false);
                            $.notify(data.message, {
                                globalPosition: "top center",
                                className : "success"
                            })
                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if (confirm('Are you sure to delete ?')) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete","Provinsi")/' + id,
                    success: function (data) {
                        if (data.success) {
                            datatable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "bottom center",
                                className: "success"
                            })
                        }
                    }
                });
            }
        }
    </script>
}