Tricone/Controllers/WisataUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tricone.Models;

namespace Tricone.Controllers
{
    public class WisataUserController : Controller
    {
        // GET: WisataUser
        DB_TRICONEEntitie db = new DB_TRICONEEntitie();
        public ActionResult Index()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 11 || x.ID_PROVINSI == 12 || x.ID_PROVINSI == 13 || x.ID_PROVINSI == 14 || x.ID_PROVINSI == 15 || x.ID_PROVINSI == 16).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }

        public ActionResult Jabar()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 12).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }
        
        public ActionResult Banten()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 11).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }

        public ActionResult jkt()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 13).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }
        public ActionResult jateng()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 14).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }
        public ActionResult jatim()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 16).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }
        public ActionResult jogja()
        {
            List<TBL_WISATA> wisataList = db.TBL_WISATA.Where(x => x.ID_PROVINSI == 15).ToList();
            ViewData["detailwisata"] = wisataList;
            return View();
        }
    }
}

Tricone/Views/WisataUser/Index.cshtml
@model IEnumerable<Tricone.Models.TBL_WISATA>
@{
    ViewBag.Title = "Index";
}
<style>
    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: absolute;
        height: 100%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #4CAF50;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }
</style>


<div class="ftco-blocks-cover-1">
    <div class="site-section section-3" style="background-image: url('@Url.Content("~/images/bushd.jpg")');">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <br />
                    <br />
                    <h1 style="color:white;">VEHICLE DETAILS</h1>
                </div>
            </div>
        </div>
    </div>
</div>

<div>
    <div class="site-section bg-light" id="contact-section">
        <div class="container">
            @*<div class="row justify-content-center text-center">
                    <div class="col-7 text-center mb-5">
                        <h1>Testimonial User</h1>
                        <p>
                            Please give your testimonial after using the tricone travel service
                        </p>
                    </div>
                </div>*@
            <div>
                <div class="sidebar">
                    <a class="active" href="@Url.Action("Index", "WisataUser")">All Province</a>
                    <a href="@Url.Action("Banten", "WisataUser")">Banten</a>
                    <a href="@Url.Action("Jabar", "WisataUser")">West Java</a>
                    <a href="@Url.Action("jkt", "WisataUser")">Jakarta</a>
                    <a href="@Url.Action("jateng", "WisataUser")">Central Java</a>
                    <a href="@Url.Action("jogja", "WisataUser")">DI Yogyakarta</a>
                    <a href="@Url.Action("jatim", "WisataUser")">East Java</a>
                </div>

                <div class="content">
                    <h1 class="text-lg-center text-white" style="background-color:slategrey">
                        <b>
                            Destination Travel Province
                        </b>
                    </h1>
                    <br />
                    <div class="row align-items-stretch">
                        <div class="col-lg-4 col-md-6 mb-5">
                            <div class="rounded">
                                <a href='@Url.Action("Banten", "WisataUser")'>
                                    <img src="@Url.Content("~/images/banten.png")" alt="Alps"
                                         class="img-fluid img-thumbnail" style="width: 500px; height: 300px;">
                                </a>
                                <div class="post-entry-1-contents text-xl-center">
                                    <br />
                                    <h2><b>BANTEN</b></h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-5">
                            <div class="rounded">
                                <a href='@Url.Action("Jabar", "WisataUser")'>
                                    <img src="@Url.Content("~/images/jabar.PNG")" alt="Alps"
                                         class="img-fluid img-thumbnail" style="width: 500px; height: 300px;">
                                </a>
                                <div class="post-entry-1-contents text-xl-center">
                                    <br />
                                    <h2><b>WEST JAVA</b></h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-5">
                            <div class="rounded">
                                <a href='@Url.Action("jkt", "WisataUser")'>
                                    <img src="@Url.Content("~/images/jkt.PNG")" alt="Alps"
                                         class="img-fluid img-thumbnail" style="width: 500px; height: 300px;">
                                </a>
                                <div class="post-entry-1-contents text-xl-center">
                                    <br />
                                    <h2><b>DKI JAKARTA</b></h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-5">
                            <div class="rounded">
                                <a href='@Url.Action("jateng", "WisataUser")'>
                                    <img src="@Url.Content("~/images/jateng.PNG")" alt="Alps"
                                         class="img-fluid img-thumbnail" style="width: 500px; height: 300px;">
                                </a>
                                <div class="post-entry-1-contents text-xl-center">
                                    <br />
                                    <h2><b>CENTRAL JAVA</b></h2>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 mb-5">
                            <div class="rounded">
                                <a href='@Url.Action("jogja", "WisataUser")'>
                                    <img src="@Url.Content("~/images/jogja.PNG")" alt="Alps"
                                         class="img-fluid img-thumbnail" style="width: 500px; height: 300px;">
                                </a>
                                <div class="post-entry-1-contents text-xl-center">
                                    <br />
                                    <h2><b>DI YOGYAKARTA</b></h2>
                                </div>
                            </div>
                        </div>
                         <div class="col-lg-4 col-md-6 mb-5">
                            <div class="rounded">
                                <a href='@Url.Action("jatim", "WisataUser")'>
                                    <img src="@Url.Content("~/images/jatim.PNG")" alt="Alps"
                                         class="img-fluid img-thumbnail" style="width: 500px; height: 300px;">
                                </a>
                                <div class="post-entry-1-contents text-xl-center">
                                    <br />
                                    <h2><b>EAST JAVA    </b></h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>

Tricone/Views/WisataUser/Jabar.cshtml
@{
    ViewBag.Title = "Jabar";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: absolute;
        height: 105%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #4CAF50;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }

    li {
        display: list-item;
    }
    .sidenav {
        height: 100%;
        width: 200px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 20px;
    }

        /* Style the sidenav links and the dropdown button */
        .sidenav a, .dropdown-btn {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            border: none;
            background: none;
            width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }
            /* On mouse-over */
            .sidenav a:hover, .dropdown-btn:hover {
                color: #f1f1f1;
            }

    /* Main content */
    .main {
        margin-left: 200px; /* Same as the width of the sidenav */
        font-size: 20px; /* Increased text to enable scrolling */
        padding: 0px 10px;
    }

    /* Add an active class to the active dropdown button */
    .active {
        background-color: green;
        color: white;
    }

</style>
<div class="ftco-blocks-cover-1">
    <div class="site-section section-3" style="background-image: url('@Url.Content("~/images/bushd.jpg")');">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <br />
                    <br />
                    <h1 style="color:white;">VEHICLE DETAILS</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="site-section 1 bg-light" id="contact-section">
        <div class="container">
            <div>
                <div class="sidebar">
                    <a href="@Url.Action("Index", "WisataUser")">All Province</a>
                    <a href="@Url.Action("Banten", "WisataUser")">Banten</a>
                    <a class="active" href="@Url.Action("Jabar", "WisataUser")">West Java</a>
                    <a href="@Url.Action("jkt", "WisataUser")">Jakarta</a>
                    <a href="@Url.Action("jateng", "WisataUser")">Central Java</a>
                    <a href="@Url.Action("jogja", "WisataUser")">DI Yogyakarta</a>
                    <a href="@Url.Action("jatim", "WisataUser")">East Java</a>
                </div>
                    @foreach (var item in ViewData["detailwisata"] as IEnumerable<Tricone.Models.TBL_WISATA>)
                    {
                        <div class="content">
                            <div class="row align-items-stretch">
                                <div class="col-lg-12 col-md-12 ml-lg-5">
                                    <h1 class="text-lg-center text-white" style="background-color:slategrey">
                                        <b>
                                            @item.NAMA_WISATA
                                        </b>
                                    </h1>
                                    <br />
                                    <div class="row">
                                        <div class="col-lg-7 mb-5">
                                            <div class="row col-12">
                                                <p class="text-justify" style="white-space: pre-line">
                                                    @item.DESKRIPSI
                                                </p>
                                            </div>
                                        </div>
                                        <div class="rounded col-lg-5 ml-auto">
                                            <a href="#"><img src="@Url.Content("~/images/"+item.FOTO_DERSKRIPSI)" alt="Image" class="img-fluid" style="width:300px; height:300px;"></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
</div>
        </div>
    </div>
</div>

Tricone/Views/WisataUser/banten.cshtml
@{
    ViewBag.Title = "banten";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: absolute;
        height: 105%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #4CAF50;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }

    li {
        display: list-item;
    }

    .sidenav {
        height: 100%;
        width: 200px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 20px;
    }

        /* Style the sidenav links and the dropdown button */
        .sidenav a, .dropdown-btn {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            border: none;
            background: none;
            width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }
            /* On mouse-over */
            .sidenav a:hover, .dropdown-btn:hover {
                color: #f1f1f1;
            }

    /* Main content */
    .main {
        margin-left: 200px; /* Same as the width of the sidenav */
        font-size: 20px; /* Increased text to enable scrolling */
        padding: 0px 10px;
    }

    /* Add an active class to the active dropdown button */
    .active {
        background-color: green;
        color: white;
    }
</style>
<div class="ftco-blocks-cover-1">
    <div class="site-section section-3" style="background-image: url('@Url.Content("~/images/bushd.jpg")');">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <br />
                    <br />
                    <h1 style="color:white;">VEHICLE DETAILS</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="site-section bg-light" id="contact-section">
        <div class="container">
            <div>
                <div class="sidebar">
                    <a href="@Url.Action("Index", "WisataUser")">All Province</a>
                    <a class="active" href="@Url.Action("Banten", "WisataUser")">Banten</a>
                    <a href="@Url.Action("Jabar", "WisataUser")">West Java</a>
                    <a href="@Url.Action("jkt", "WisataUser")">Jakarta</a>
                    <a href="@Url.Action("jateng", "WisataUser")">Central Java</a>
                    <a href="@Url.Action("jogja", "WisataUser")">DI Yogyakarta</a>
                    <a href="@Url.Action("jatim", "WisataUser")">East Java</a>
                </div>
                @foreach (var item in ViewData["detailwisata"] as IEnumerable<Tricone.Models.TBL_WISATA>)
                {
                    
                    <div class="content">
                        <div class="row align-items-stretch">
                            <div class="col-lg-12 col-md-12 ml-lg-5">
                                <h1 class="text-lg-center text-white" style="background-color:slategrey">
                                    <b>
                                        @item.NAMA_WISATA
                                    </b>
                                </h1>
                                <br />
                                <div class="row">
                                    <div class="col-lg-7 mb-5">
                                        <div class="row col-12">
                                            <p class="text-justify" style="white-space: pre-line">
                                                @item.DESKRIPSI
                                            </p>
                                        </div>
                                    </div>
                                    <div class="rounded col-lg-5 ml-auto">
                                        <a href="#"><img src="@Url.Content("~/images/"+item.FOTO_DERSKRIPSI)" alt="Image" class="img-fluid" style="width:300px; height:300px;"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Tricone/Views/WisataUser/jateng.cshtml
@{
    ViewBag.Title = "jateng";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: absolute;
        height: 105%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #4CAF50;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }

    li {
        display: list-item;
    }

    .sidenav {
        height: 100%;
        width: 200px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 20px;
    }

        /* Style the sidenav links and the dropdown button */
        .sidenav a, .dropdown-btn {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            border: none;
            background: none;
            width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }
            /* On mouse-over */
            .sidenav a:hover, .dropdown-btn:hover {
                color: #f1f1f1;
            }

    /* Main content */
    .main {
        margin-left: 200px; /* Same as the width of the sidenav */
        font-size: 20px; /* Increased text to enable scrolling */
        padding: 0px 10px;
    }

    /* Add an active class to the active dropdown button */
    .active {
        background-color: green;
        color: white;
    }
</style>
<div class="ftco-blocks-cover-1">
    <div class="site-section section-3" style="background-image: url('@Url.Content("~/images/bushd.jpg")');">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <br />
                    <br />
                    <h1 style="color:white;">VEHICLE DETAILS</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="site-section 1 bg-light" id="contact-section">
        <div class="container">
            <div>
                <div class="sidebar">
                    <a href="@Url.Action("Index", "WisataUser")">All Province</a>
                    <a href="@Url.Action("Banten", "WisataUser")">Banten</a>
                    <a href="@Url.Action("Jabar", "WisataUser")">West Java</a>
                    <a href="@Url.Action("jkt", "WisataUser")">Jakarta</a>
                    <a class="active" href="@Url.Action("jateng", "WisataUser")">Central Java</a>
                    <a href="@Url.Action("jogja", "WisataUser")">DI Yogyakarta</a>
                    <a href="@Url.Action("jatim", "WisataUser")">East Java</a>
                </div>
                @foreach (var item in ViewData["detailwisata"] as IEnumerable<Tricone.Models.TBL_WISATA>)
                {
                    <div class="content">
                        <div class="row align-items-stretch">
                            <div class="col-lg-12 col-md-12 ml-lg-5">
                                <h1 class="text-lg-center text-white" style="background-color:slategrey">
                                    <b>
                                        @item.NAMA_WISATA
                                    </b>
                                </h1>
                                <br />
                                <div class="row">
                                    <div class="col-lg-7 mb-5">
                                        <div class="row col-12">
                                            <p class="text-justify" style="white-space: pre-line">
                                                @item.DESKRIPSI
                                            </p>
                                        </div>
                                    </div>
                                    <div class="rounded col-lg-5 ml-auto">
                                        <a href="#"><img src="@Url.Content("~/images/"+item.FOTO_DERSKRIPSI)" alt="Image" class="img-fluid" style="width:300px; height:300px;"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

Tricone/Views/WisataUser/jatim.cshtml
@{
    ViewBag.Title = "jatim";
}

<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<style>
    body {
        margin: 0;
        font-family: "Lato", sans-serif;
    }

    .sidebar {
        margin: 0;
        padding: 0;
        width: 200px;
        background-color: #f1f1f1;
        position: absolute;
        height: 105%;
        overflow: auto;
    }

        .sidebar a {
            display: block;
            color: black;
            padding: 16px;
            text-decoration: none;
        }

            .sidebar a.active {
                background-color: #4CAF50;
                color: white;
            }

            .sidebar a:hover:not(.active) {
                background-color: #555;
                color: white;
            }

    div.content {
        margin-left: 200px;
        padding: 1px 16px;
        height: 1000px;
    }

    li {
        display: list-item;
    }

    .sidenav {
        height: 100%;
        width: 200px;
        position: fixed;
        z-index: 1;
        top: 0;
        left: 0;
        background-color: #111;
        overflow-x: hidden;
        padding-top: 20px;
    }

        /* Style the sidenav links and the dropdown button */
        .sidenav a, .dropdown-btn {
            padding: 6px 8px 6px 16px;
            text-decoration: none;
            font-size: 20px;
            color: #818181;
            display: block;
            border: none;
            background: none;
            width: 100%;
            text-align: left;
            cursor: pointer;
            outline: none;
        }
            /* On mouse-over */
            .sidenav a:hover, .dropdown-btn:hover {
                color: #f1f1f1;
            }

    /* Main content */
    .main {
        margin-left: 200px; /* Same as the width of the sidenav */
        font-size: 20px; /* Increased text to enable scrolling */
        padding: 0px 10px;
    }

    /* Add an active class to the active dropdown button */
    .active {
        background-color: green;
        color: white;
    }
</style>
<div class="ftco-blocks-cover-1">
    <div class="site-section section-3" style="background-image: url('@Url.Content("~/images/bushd.jpg")');">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-6 text-center">
                    <br />
                    <br />
                    <h1 style="color:white;">VEHICLE DETAILS</h1>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <div class="site-section 1 bg-light" id="contact-section">
        <div class="container">
            <div>
                <div class="sidebar">
                    <a href="@Url.Action("Index", "WisataUser")">All Province</a>
                    <a href="@Url.Action("Banten", "WisataUser")">Banten</a>
                    <a href="@Url.Action("Jabar", "WisataUser")">West Java</a>
                    <a href="@Url.Action("jkt", "WisataUser")">Jakarta</a>
                    <a href="@Url.Action("jateng", "WisataUser")">Central Java</a>
                    <a href="@Url.Action("jogja", "WisataUser")">DI Yogyakarta</a>
                    <a class="active" href="@Url.Action("jatim", "WisataUser")">East Java</a>
                </div>
                @foreach (var item in ViewData["detailwisata"] as IEnumerable<Tricone.Models.TBL_WISATA>)
                {
                    <div class="content">
                        <div class="row align-items-stretch">
                            <div class="col-lg-12 col-md-12 ml-lg-5">
                                <h1 class="text-lg-center text-white" style="background-color:slategrey">
                                    <b>
                                        @item.NAMA_WISATA
                                    </b>
                                </h1>
                                <br />
                                <div class="row">
                                    <div class="col-lg-7 mb-5">
                                        <div class="row col-12">
                                            <p class="text-justify" style="white-space: pre-line">
                                                @item.DESKRIPSI
                                            </p>
                                        </div>
                                    </div>
                                    <div class="rounded col-lg-5 ml-auto">
                                        <a href="#"><img src="@Url.Content("~/images/"+item.FOTO_DERSKRIPSI)" alt="Image" class="img-fluid" style="width:300px; height:300px;"></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>