Tricone/Controllers/WisataController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tricone.Models;

namespace Tricone.Controllers
{
    public class wisataController : Controller
    {
        // GET: wisata
        DB_TRICONEEntitie dc = new DB_TRICONEEntitie();

        public ActionResult Index()
        {
            return View(dc.TBL_WISATA.ToList());
        }


        [HttpGet]
        public JsonResult Getdata()
        {
            List<TBL_WISATA> wisatalist = dc.TBL_WISATA.ToList<TBL_WISATA>();
            List<wisataOutput> result = new List<wisataOutput>();
            foreach (var item in wisatalist)
            {
                result.Add(new wisataOutput
                {
                    ID_PROVINSI = item.ID_PROVINSI,
                    NAMA_PROVINSI = item.MS_PROVINSI.NAMA_PROVINSI,
                    ID_KOTA = item.ID_KOTA,
                    NAMA_KOTA = item.MS_KOTA.NAMA_KOTA,
                    ID_WISATA = item.ID_WISATA,
                    NAMA_WISATA = item.NAMA_WISATA,
                    DESKRIPSI = item.DESKRIPSI,
                    FOTO_DERSKRIPSI = item.FOTO_DERSKRIPSI
                });
            }

            //var json = Newtonsoft.Json.JsonConvert.SerializeObject(result);
            return Json(new { data = result.OrderByDescending(e => e.ID_KOTA) }, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult AddorEdit(int id = 0)
        {
            TBL_WISATA wisatamodel = new TBL_WISATA();
            wisatamodel.provcollection = dc.MS_PROVINSI.ToList<MS_PROVINSI>();
            wisatamodel.kotacollection = dc.MS_KOTA.ToList<MS_KOTA>();
            if (id == 0)
            {
                //return View(new MS_KOTA());
                return View(wisatamodel);
            }
            else
            {
                wisatamodel = dc.TBL_WISATA.Where(x => x.ID_WISATA == id).FirstOrDefault();
                wisatamodel.provcollection = dc.MS_PROVINSI.ToList<MS_PROVINSI>();
                wisatamodel.kotacollection = dc.MS_KOTA.ToList<MS_KOTA>();
                //return View(dc.MS_KOTA.Where(x => x.ID_KOTA == id).FirstOrDefault<MS_KOTA>());
                return View(wisatamodel);
            }
        }

        [HttpPost]
        public ActionResult AddorEdit(TBL_WISATA wisata, HttpPostedFileBase filebase)
        {
            using (var transactions = dc.Database.BeginTransaction())
            {
                try
                {
                    wisata.UPDATE_DATE = DateTime.Now;
                    if (wisata.ID_WISATA == 0)
                    {
                        string fileName = Path.GetFileNameWithoutExtension(filebase.FileName);
                        string extension = Path.GetExtension(filebase.FileName);
                        fileName = fileName + DateTime.Now.ToString("yyyyMMddHHmmssfff") + extension;
                        wisata.FOTO_DERSKRIPSI = fileName;
                        fileName = Path.Combine(Server.MapPath("~/images/"), fileName);
                        filebase.SaveAs(fileName);
                        wisata.CREATED_DATE = DateTime.Now;
                        if (filebase.ContentLength <= 1000000)
                        {
                            dc.TBL_WISATA.Add(wisata);
                            if (dc.SaveChanges() > 0)
                            {
                                filebase.SaveAs(fileName);

                                //audit trail
                                var wisat = dc.TBL_WISATA.OrderByDescending(e => e.ID_WISATA).FirstOrDefault();
                                TBL_AUDIT_TRAIL audit = new TBL_AUDIT_TRAIL();
                                audit.NAMA_TABEL = "TBL_WISATA";
                                audit.AKSI = "ADD";
                                audit.NAMA_FIELD = "All Field";
                                audit.VALUE_LAMA = "";
                                audit.userid = Session["ID_MEMBER"].ToString();
                                audit.VALUE_BARU = wisat.ID_PROVINSI + ", " + wisat.ID_KOTA + ", " + wisat.ID_WISATA + ", " + wisat.NAMA_WISATA + ", " + wisat.DESKRIPSI + ", " + wisat.FOTO_DERSKRIPSI;
                                audit.CREATED_DATE = DateTime.Now;
                                audit.MODIFIED_DATE = DateTime.Now;
                                dc.TBL_AUDIT_TRAIL.Add(audit);
                                dc.SaveChanges();

                                transactions.Commit();
                                return Json(new { success = true, message = "Saved Successfully" }, JsonRequestBehavior.AllowGet);
                            }
                        
                            else
                            {
                                return Json(new { success = true, message = "File Size must be Equal or less than 1mb" }, JsonRequestBehavior.AllowGet);
                                //ViewBag.msg = "File Size must be Equal or less than 1mb";
                            }
                        }
                        else
                        {
                            return Json(new { success = true, message = "Please Try Again With Short Filename" }, JsonRequestBehavior.AllowGet);
                        }
                    }
                    else
                    {
                        var qaudit = dc.TBL_WISATA.AsNoTracking().Where(x => x.ID_WISATA == wisata.ID_WISATA).FirstOrDefault();
                        TBL_AUDIT_TRAIL audit = new TBL_AUDIT_TRAIL();

                        if (filebase != null)
                        {
                            //delete foto lama
                            string fullPath = Request.MapPath("~/images/" + wisata.FOTO_DERSKRIPSI);
                            if (System.IO.File.Exists(fullPath))
                            {
                                System.IO.File.Delete(fullPath);
                            }

                            //penambahan foto baru
                            string fileName = Path.GetFileNameWithoutExtension(filebase.FileName);
                            string extension = Path.GetExtension(filebase.FileName);
                            fileName = fileName + DateTime.Now.ToString("yyyyMMddHHmmssfff") + extension;
                            //if (kendaraan.FOTO_PROMO==null) { kendaraan.FOTO_PROMO = fileName; }
                            wisata.FOTO_DERSKRIPSI = fileName;
                            fileName = Path.Combine(Server.MapPath("~/images/"), fileName);
                            filebase.SaveAs(fileName);

                            audit.VALUE_LAMA = qaudit.ID_PROVINSI + ", " + qaudit.ID_KOTA + ", " + qaudit.ID_WISATA + ", " + qaudit.NAMA_WISATA + ", " + qaudit.DESKRIPSI + ", " + qaudit.FOTO_DERSKRIPSI;
                            audit.VALUE_BARU = wisata.ID_PROVINSI + ", " + wisata.ID_KOTA + ", " + wisata.ID_WISATA + ", " + wisata.NAMA_WISATA + ", " + wisata.DESKRIPSI + ", " + wisata.FOTO_DERSKRIPSI;
                        }

                        dc.Entry(wisata).State = EntityState.Modified;
                        if (filebase == null)
                        {
                            dc.Entry(wisata).Property("FOTO_DERSKRIPSI").IsModified = false;

                            audit.VALUE_LAMA = qaudit.ID_PROVINSI + ", " + qaudit.ID_KOTA + ", " + qaudit.ID_WISATA + ", " + qaudit.NAMA_WISATA + ", " + qaudit.DESKRIPSI + ", " + qaudit.FOTO_DERSKRIPSI;
                            audit.VALUE_BARU = wisata.ID_PROVINSI + ", " + wisata.ID_KOTA + ", " + wisata.ID_WISATA + ", " + wisata.NAMA_WISATA + ", " + wisata.DESKRIPSI + ", " + wisata.FOTO_DERSKRIPSI;
                        }
                        dc.Entry(wisata).Property("CREATED_DATE").IsModified = false;
                        dc.SaveChanges();

                        //audit trail edit
                        audit.NAMA_TABEL = "TBL_PROMO";
                        audit.AKSI = "EDIT";
                        audit.userid = Session["ID_MEMBER"].ToString();
                        audit.NAMA_FIELD = "";
                        audit.CREATED_DATE = DateTime.Now;
                        audit.MODIFIED_DATE = DateTime.Now;
                        dc.TBL_AUDIT_TRAIL.Add(audit);
                        dc.SaveChanges();

                        transactions.Commit();
                        return Json(new { success = true, message = "Updated Successfully" }, JsonRequestBehavior.AllowGet);
                    }
                }
                catch (Exception msgErr)
                {
                    //error log
                    DB_TRICONEEntitie dc2 = new DB_TRICONEEntitie();
                    TBL_EROR_LOG logerror = new TBL_EROR_LOG();
                    if (Convert.ToInt32(Session["ID_MEMBER"])> 0)
                    {
                        logerror.ID_USER = Session["ID_MEMBER"].ToString();
                    }
                    logerror.EROR_TIME = DateTime.Now;
                    logerror.EROR_DESCRIPTION = msgErr.Message;
                    logerror.CREATED_DATE = DateTime.Now;
                    logerror.MODIFIED_DATE = DateTime.Now;
                    logerror.EROR_LINE = Convert.ToString(string.Format("StackTrace: {0}", msgErr.StackTrace));
                    dc2.TBL_EROR_LOG.Add(logerror);
                    dc2.SaveChanges();

                    transactions.Rollback();
                    return Json(new { success = true, message = msgErr.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            TBL_WISATA wisata = dc.TBL_WISATA.Where(x => x.ID_WISATA == id).FirstOrDefault<TBL_WISATA>();
            dc.TBL_WISATA.Remove(wisata);
            dc.SaveChanges();
            return Json(new { success = true, message = "Deleted Successfully" }, JsonRequestBehavior.AllowGet);

Tricone/Views/Wisata/AddorEdit.cshtml
@model Tricone.Models.TBL_WISATA

@{
    Layout = null;
}

@using (Html.BeginForm("AddOrEdit", "wisata", FormMethod.Post, new { onsubmit = "return SubmitForm(this)", enctype = "multipart/form-data" }))
{
    @Html.HiddenFor(model => model.ID_WISATA)
    <div class="form-group">
        <div class="col-md-12">
            <label class="control-label">Province Name<span style="color:red;"> *</span></label>
            <span style="color:red;">@Html.ValidationMessageFor(model => model.ID_PROVINSI)</span>
            @Html.DropDownListFor(Model => Model.ID_PROVINSI, new SelectList((from c in Model.provcollection.ToList() where c.ID_PROVINSI == 11 || c.ID_PROVINSI == 12 || c.ID_PROVINSI == 13 || c.ID_PROVINSI == 14 || c.ID_PROVINSI == 15 || c.ID_PROVINSI == 16 select new { nama_provinsi = c.NAMA_PROVINSI, id_provinsi= c.ID_PROVINSI }), "id_provinsi", "nama_provinsi"), "Select City", new { @class = "form-control select2" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <label class="control-label">City Name<span style="color:red;"> *</span></label>
            <span style="color:red;">@Html.ValidationMessageFor(model => model.ID_KOTA)</span>
            @Html.DropDownListFor(Model => Model.ID_KOTA, new SelectList(Model.kotacollection, "ID_KOTA", "NAMA_KOTA"), "Select City", new { @class = "form-control select2" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <label class="control-label">Destination Name<span style="color:red;"> *</span></label>
            @Html.EditorFor(model => model.NAMA_WISATA, new { htmlAttributes = new { @class = "form-control col-md-12", @placeholder = "Destination Name" } })
            <span style="color:red;">@Html.ValidationMessageFor(model => model.NAMA_WISATA)</span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-12">
            <label class="control-label">Description<span style="color:red;"> *</span></label>
            @Html.TextAreaFor(model => model.DESKRIPSI, new { htmlAttributes = new { @class = "form-control col-md-12", @placeholder = "Description", cols = 35, @rows = 3 } })
            <span style="color:red;">@Html.ValidationMessageFor(model => model.DESKRIPSI)</span>
        </div>
    </div>
    <div class="form-group">
        <div class="@(Model.ID_WISATA != 0 ? "col-md-8" : "col-md-12")">
            <label class="control-label">Image<span style="color:red;"> *</span></label>
            <span style="color:red;">@Html.ValidationMessageFor(model => model.FOTO_DERSKRIPSI)</span>
            <div class="form-control col-md-12">
                <input type="file" name="filebase" onchange="fileCheck(this);" @(Model.ID_WISATA == 0 ? "required" : "") />
            </div>
        </div>
        @if (Model.ID_WISATA != 0)
        {
            @Html.HiddenFor(model => model.FOTO_DERSKRIPSI)
            <div class="col-md-4" style="margin-top:10px;">
                <img src="@Url.Content("~/images/"+Model.FOTO_DERSKRIPSI)" width="100" height="100" />
            </div>
        }
    </div>
    <div class="form-label-group">
        <div class="container col-sm-12" style="margin-top:10px;">
            <input type="submit" value="submit" class="btn btn-primary" />
            <input type="reset" value="reset" class="btn btn-warning" />
        </div>
    </div>
}

Tricone/Views/Wisata/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<link href="~/plugins/select2/select2.min.css" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="~/Content/jquery-ui.min.css" />

<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1>
            Travel Destination
        </h1>
        @*<ol class="breadcrumb">
                <li><a href="#"><i class="fa fa-database"></i>Master Data</a></li>
                <li class="active">Service</li>
            </ol>*@
    </section>

    <!-- Main content -->
    <section class="content">
        <a class="btn btn-success" style="margin-bottom:10px" onclick="PopupForm('@Url.Action("AddorEdit","wisata")')"><i class="fa fa-plus"></i> Create New</a>
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                    </div><!-- /.box-header -->
                    <div class="box-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th style='text-align: center;'>
                                        Province Name
                                    </th>
                                    <th style='text-align: center;'>
                                        City Name
                                    </th>
                                    <th style='text-align: center;'>
                                        Destination Name
                                    </th>
                                    <th style='text-align: center;'>
                                        Description
                                    </th>
                                    <th style='text-align: center;'>
                                        Image
                                    </th>
                                    <th style='text-align: center;'>
                                        Action
                                    </th>
                                </tr>
                            </thead>
                        </table>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->
            </div><!-- /.col -->
        </div><!-- /.row -->
    </section><!-- /.content -->
</div><!-- /.content-wrapper -->

@section scripts{
    <script src="~/Scripts/jquery-ui-1.12.1.min.js" crossorigin="anonymous"></script>
    <script src="~/plugins/select2/select2.full.min.js" type="text/javascript"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/notify.min.js"></script>
    <script type="text/javascript">

        var Popup, dataTable;
        $(document).ready(function () {
            datatable = $('#example1').DataTable({
                "ajax": {
                    "url": "@Url.Action("Getdata", "wisata")",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    { "data": "NAMA_PROVINSI" },
                    { "data": "NAMA_KOTA" },
                    { "data": "NAMA_WISATA" },
                    { "data": "DESKRIPSI" },
                    {
                        "data": "FOTO_DERSKRIPSI", "render": function (data) {
                            var ROOT = '@Url.Content("~/images/")';
                            return "<div style='text-align:center;'><img src='" + ROOT + data +"' width='80' height='80' class='img-rounded'/></div>";
                        }
                    },
                    {
                        "data": "ID_WISATA", "render": function (data) {
                            return "<div style= 'text-align: center;'><a class='btn btn-primary btn-sm' onclick=PopupForm('@Url.Action("AddOrEdit", "wisata")/" + data + "')><i class='fa fa-pencil'></i> Edit</a></div> "
                        },
                        "orderable": false,
                        "width":"150px"
                    }
                ], "order": [],
                "language": {
                    "emptyTable":"No Data Found, Please click on <b>Create New</b> Button"
                }
            });
        });

        function PopupForm(url) {
            var formDiv = $('<div/>');
            $.get(url)
                .done(function (response) {
                    formDiv.html(response);

                    Popup = formDiv.dialog({
                        autoOpen: true,
                        resizable: false,
                        title: 'Fill City Details',
                        height: 500,
                        width: 500,
                        open: function () {
                            if ($.ui && $.ui.dialog && !$.ui.dialog.prototype._allowInteractionRemapped && $(this).closest(".ui-dialog").length) {
                                if ($.ui.dialog.prototype._allowInteraction) {
                                    $.ui.dialog.prototype._allowInteraction = function (e) {
                                        if ($(e.target).closest('.select2-drop').length) return true;
                                        return ui_dialog_interaction.apply(this, arguments);
                                    };
                                    $.ui.dialog.prototype._allowInteractionRemapped = true;
                                }
                                else {
                                    $.error("You must upgrade jQuery UI or else.");
                                }
                            }
                        },
                        _allowInteraction: function (event) {
                            return !!$(event.target).is(".select2-input") || this._super(event);
                        },
                        close: function () {
                            Popup.dialog('destroy').remove();
                        }
                    });
                    $(".select2").select2();
                });
        }

        function SubmitForm(form) {
            $.validator.unobtrusive.parse(form);
            if ($(form).valid()) {
                var formData = new FormData($(form)[0]);
                $.ajax({
                    type: "POST",
                    url: form.action,
                    data: formData,
                    processData: false,
                    contentType: false,
                    success: function (data) {
                        if (data.success) {
                            Popup.dialog('close');
                            datatable.ajax.reload(null, false);

                            $.notify(data.message, {
                                globalPosition: "top center",
                                className : "success"
                            })
                        }
                    }
                });
            }
            return false;
        }

        function Delete(id) {
            if (confirm('Are you sure to delete ?')) {
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("Delete", "wisata")/' + id,
                    success: function (data) {
                        if (data.success) {
                            datatable.ajax.reload();

                            $.notify(data.message, {
                                globalPosition: "bottom center",
                                className: "success"
                            })
                        }
                    }
                });
            }
        }
    </script>
}